/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package regression_test

import (
	"embed"
	"encoding/base64"
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"

	math "github.com/IBM/mathlib"
	"github.com/LFDT-Panurus/panurus/token"
	"github.com/LFDT-Panurus/panurus/token/core"
	"github.com/LFDT-Panurus/panurus/token/core/common"
	fabtoken "github.com/LFDT-Panurus/panurus/token/core/fabtoken/v1/driver"
	"github.com/LFDT-Panurus/panurus/token/core/zkatdlog/nogh/v1/audit"
	dlog "github.com/LFDT-Panurus/panurus/token/core/zkatdlog/nogh/v1/driver"
	"github.com/LFDT-Panurus/panurus/token/core/zkatdlog/nogh/v1/setup"
	testing2 "github.com/LFDT-Panurus/panurus/token/core/zkatdlog/nogh/v1/testutils"
	"github.com/LFDT-Panurus/panurus/token/driver"
	"github.com/LFDT-Panurus/panurus/token/services/logging"
	"github.com/LFDT-Panurus/panurus/token/services/network/fabric/tcc"
	tk "github.com/LFDT-Panurus/panurus/token/token"
	"github.com/hyperledger-labs/fabric-smart-client/pkg/utils/errors"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/trace/noop"
)

//go:embed testdata
var testDataFS embed.FS

// ValidationFunc is a function that validates the results of UnmarshallAndVerifyWithMetadata.
// It receives the actions and metadata returned by the validator and returns an error if validation fails.
type ValidationFunc func(actions []any, metadata map[string][]byte) error

// TestRegression runs previously recorded regression test vectors contained in the
// `testdata/<variant>` directories. Each configuration directory contains a `params.txt`
// file with base64-encoded public parameters and a single `testdata.json` file with all
// test cases for that configuration.
//
// The `testdata.json` file contains labeled test cases in an aggregated format:
//
//	{
//	  "transfers_i1_o1_0": {"req_raw": "<base64>", "txid": "...", "metadata": "<base64>", "inputs": [...]},
//	  "transfers_i1_o1_1": {...},
//	  ...
//	  "issues_i1_o1_0": {...},
//	  "redeems_i2_o2_63": {...},
//	  "swaps_i2_o2_63": {...},
//	  "upgrade_witness_0": {...},
//	  "pub_metadata_issue_0": {...},
//	  "pub_metadata_transfer_0": {...},
//	  "unclaimed_metadata_0": {...},
//	  "multi_auditor_0": {...},
//	  "extra_signature_0": {...}
//	}
//
// Test case keys follow the pattern: `<action>_i<inputs>_o<outputs>_<index>` for the
// swept action types (transfers, issues, redeems, swaps), or `<scenario>_<index>` for
// the single fixed-shape scenario fixtures (upgrade_witness, pub_metadata_issue,
// pub_metadata_transfer, unclaimed_metadata, multi_auditor, extra_signature). The
// open_policy_issue/open_policy_redeem scenario lives in its own root (see below).
//
// unclaimed_metadata_* and extra_signature_* are NEGATIVE fixtures: validation is
// expected to fail (see negativeFixtureErrorSubstr) rather than succeed.
//
// The test unmarshals each test case and verifies it against the validator to ensure
// the library remains backwards compatible. Two range-proof systems are covered:
// the IPA/bulletproof vectors under `testdata/zero/<config>` and the CSP vectors
// under `testdata/zero/csp/<config>`. The open-issuer-policy vectors (gap 3) live
// under `testdata/zero/open-policy/<config>` and are generated only for the IPA
// proof type, since issuer policy is orthogonal to the range-proof system.
//
// Notes:
//   - The testdata is generated by `testdata/zero/generator`. To regenerate vectors,
//     run that generator (default = IPA; `-proof_type=csp` for CSP) and commit the
//     produced `testdata.json` files.
//   - Each test case includes the token request, transaction ID, metadata, and input tokens.
func TestRegression(t *testing.T) {
	t.Parallel()

	// Test configurations, shared across range-proof systems.
	configurations := []string{
		"32-BLS12_381_BBS_GURVY",
		"32-BN254",
		"64-BLS12_381_BBS_GURVY",
		"64-BN254",
	}

	// Each root holds one range-proof system's vectors: the IPA/bulletproof
	// vectors at testdata/zero, the CSP vectors at testdata/zero/csp, and the
	// open-issuer-policy (gap 3) vectors at testdata/zero/open-policy.
	roots := []string{
		filepath.Join("testdata", "zero"),
		filepath.Join("testdata", "zero", "csp"),
		filepath.Join("testdata", "zero", "open-policy"),
	}

	for _, root := range roots {
		for _, config := range configurations {
			configDir := filepath.Join(root, config)
			testRegressionParallel(t, configDir)
		}
	}
}

func testRegressionParallel(t *testing.T, configDir string) {
	t.Helper()
	t.Run(configDir, func(t *testing.T) {
		t.Parallel()
		testRegression(t, configDir)
	})
}

func testRegression(t *testing.T, configDir string) {
	t.Helper()
	t.Logf("regression test for [%s]", configDir)

	// Read public parameters
	paramsData, err := testDataFS.ReadFile(filepath.Join(configDir, "params.txt"))
	require.NoError(t, err)

	ppRaw, err := base64.StdEncoding.DecodeString(string(paramsData))
	require.NoError(t, err)

	pp, tokenValidator, err := tokenServicesFactory(ppRaw)
	require.NoError(t, err)

	// Create auditor for metadata validation
	auditor := createAuditor(pp)

	// Read aggregated test data file
	filePath := filepath.Join(configDir, "testdata.json")
	jsonData, err := testDataFS.ReadFile(filePath)
	require.NoError(t, err, "failed to read aggregated test data from [%s]", filePath)

	// Parse aggregated test cases
	var allTestCases map[string]testing2.TestCase
	err = json.Unmarshal(jsonData, &allTestCases)
	require.NoError(t, err, "failed to unmarshal aggregated test data from [%s]", filePath)

	// Process each test case
	for testCaseKey, tokenData := range allTestCases {
		// Decode base64-encoded request
		reqRaw, err := base64.StdEncoding.DecodeString(tokenData.ReqRaw)
		require.NoError(t, err, "failed to decode req_raw for test case %s", testCaseKey)

		// Negative fixtures (unclaimed_metadata_*, extra_signature_*) must fail
		// validation with a specific error, rather than succeed; there is no
		// action/metadata to run further checks against once validation fails.
		if wantErrSubstr, isNegative := negativeFixtureErrorSubstr(testCaseKey); isNegative {
			_, _, err := tokenValidator.UnmarshallAndVerifyWithMetadata(
				t.Context(),
				&fakeLedger{},
				token.RequestAnchor(tokenData.TxID),
				reqRaw,
			)
			require.Error(t, err, "expected validation failure for negative test case %s", testCaseKey)
			require.Contains(t, err.Error(), wantErrSubstr, "unexpected error for negative test case %s", testCaseKey)

			continue
		}

		// Determine validation function based on test case key prefix
		var validateFunc ValidationFunc
		switch {
		case strings.HasPrefix(testCaseKey, "transfers"):
			validateFunc = validateTransfers
		case strings.HasPrefix(testCaseKey, "upgrade_witness"):
			validateFunc = validateTransfers
		case strings.HasPrefix(testCaseKey, "pub_metadata_issue"):
			validateFunc = validateIssues
		case strings.HasPrefix(testCaseKey, "pub_metadata_transfer"):
			validateFunc = validateTransfers
		case strings.HasPrefix(testCaseKey, "multi_auditor"):
			validateFunc = validateTransfers
		case strings.HasPrefix(testCaseKey, "open_policy_issue"):
			validateFunc = validateIssues
		case strings.HasPrefix(testCaseKey, "open_policy_redeem"):
			validateFunc = validateOpenPolicyRedeem
		case strings.HasPrefix(testCaseKey, "issues"):
			validateFunc = validateIssues
		case strings.HasPrefix(testCaseKey, "redeems"):
			validateFunc = validateRedeems
		case strings.HasPrefix(testCaseKey, "swaps"):
			validateFunc = validateSwaps
		default:
			t.Fatalf("unknown test case type for key: %s", testCaseKey)
		}

		actions, metadata, err := tokenValidator.UnmarshallAndVerifyWithMetadata(
			t.Context(),
			&fakeLedger{},
			token.RequestAnchor(tokenData.TxID),
			reqRaw,
		)
		require.NoError(t, err, "failed verification of the token request for test case %s", testCaseKey)

		// Validate the results
		err = validateFunc(actions, metadata)
		require.NoError(t, err, "validation failed for token request for test case %s", testCaseKey)

		metadataRaw, err := base64.StdEncoding.DecodeString(tokenData.Metadata)
		require.NoError(t, err, "failed to decode metadata for test case %s", testCaseKey)

		// Perform auditor validation
		requestMetadata := new(driver.TokenRequestMetadata)
		err = requestMetadata.FromBytes(metadataRaw)
		require.NoError(t, err, "failed to unmarshal metadata for test case %s", testCaseKey)

		// Deserialize token request for auditor check
		tokenRequest := &driver.TokenRequest{}
		err = tokenRequest.FromBytes(reqRaw)
		require.NoError(t, err, "failed to deserialize token request for test case %s", testCaseKey)

		// Perform auditor check with auditTokens
		err = auditor.Check(
			t.Context(),
			tokenRequest,
			requestMetadata,
			driver.TokenRequestAnchor(tokenData.TxID),
			tokenData.Inputs.Inputs,
		)
		require.NoError(t, err, "auditor check failed for token request for test case %s", testCaseKey)
	}
}

func tokenServicesFactory(bytes []byte) (tcc.PublicParameters, tcc.Validator, error) {
	is := core.NewValidatorDriverService(driver.DefaultResourceLimits(), fabtoken.NewValidatorDriver(), dlog.NewValidatorDriver())

	ppm, err := is.PublicParametersFromBytes(bytes)
	if err != nil {
		return nil, nil, err
	}
	if err := ppm.Validate(); err != nil {
		return nil, nil, err
	}
	v, err := is.NewValidator(ppm)
	if err != nil {
		return nil, nil, err
	}

	return ppm, token.NewValidator(v), nil
}

// createAuditor creates an auditor instance for the given public parameters
func createAuditor(pp tcc.PublicParameters) *audit.Auditor {
	// Cast to concrete type to access curve and other fields
	v1pp, ok := pp.(*setup.PublicParams)
	if !ok {
		panic("expected setup.PublicParams")
	}

	c := math.Curves[v1pp.Curve]
	deserializer, err := dlog.NewDeserializer(v1pp)
	if err != nil {
		panic(err)
	}

	return audit.NewAuditor(
		logging.MustGetLogger(),
		&noop.Tracer{},
		deserializer,
		v1pp.PedersenGenerators,
		c,
		64,
		v1pp.IssuerIDs,
	)
}

// negativeFixtureErrorSubstr returns the expected validation-error substring
// for a known negative-fixture test case key prefix, and whether the key
// matches one. Negative fixtures (unclaimed_metadata_*, extra_signature_*)
// are expected to fail UnmarshallAndVerifyWithMetadata rather than succeed.
func negativeFixtureErrorSubstr(testCaseKey string) (string, bool) {
	switch {
	case strings.HasPrefix(testCaseKey, "unclaimed_metadata"):
		return "more metadata than those validated", true
	case strings.HasPrefix(testCaseKey, "extra_signature"):
		return "unconsumed signatures", true
	default:
		return "", false
	}
}

func validateMetadata(metadata map[string][]byte) error {
	if len(metadata) < 2 {
		return errors.Errorf("expected at least 2 metadata entries, got %d", len(metadata))
	}

	requiredKeys := []driver.ValidationAttributeID{
		common.TokenRequestToSign,
		common.TokenRequestSignatures,
	}
	for _, key := range requiredKeys {
		value, ok := metadata[key]
		if !ok {
			return errors.Errorf("missing metadata entry %q", key)
		}
		if len(value) == 0 {
			return errors.Errorf("metadata entry %q is empty", key)
		}
	}

	return nil
}

func validateOutputs(outputs []driver.Output, expectedNumOutputs int, expectedRedeemOutputs int) error {
	if len(outputs) != expectedNumOutputs {
		return errors.Errorf("expected %d outputs, got %d", expectedNumOutputs, len(outputs))
	}

	redeemOutputs := 0
	for i, output := range outputs {
		if output == nil {
			return errors.Errorf("output %d is nil", i)
		}
		if output.IsRedeem() {
			redeemOutputs++
			if len(output.GetOwner()) != 0 {
				return errors.Errorf("redeem output %d has unexpected owner", i)
			}

			continue
		}
		if len(output.GetOwner()) == 0 {
			return errors.Errorf("non-redeem output %d has empty owner", i)
		}
	}

	if redeemOutputs != expectedRedeemOutputs {
		return errors.Errorf("expected %d redeem outputs, got %d", expectedRedeemOutputs, redeemOutputs)
	}

	return nil
}

// validateIssues validates that the actions match the issue requests generated in env.go.
func validateIssues(actions []any, metadata map[string][]byte) error {
	if len(actions) != 1 {
		return errors.Errorf("expected 1 action for issues, got %d", len(actions))
	}

	issueAction, ok := actions[0].(driver.IssueAction)
	if !ok {
		return errors.Errorf("action does not implement driver.IssueAction interface, got type %T", actions[0])
	}
	if issueAction.NumInputs() != 0 {
		return errors.Errorf("expected issue action to have 0 inputs, got %d", issueAction.NumInputs())
	}
	if issueAction.IsAnonymous() {
		return errors.Errorf("expected issue action to be non-anonymous")
	}
	if issueAction.IsGraphHiding() {
		return errors.Errorf("expected issue action to be non-graph-hiding")
	}
	if len(issueAction.GetIssuer()) == 0 {
		return errors.Errorf("expected issue action issuer to be set")
	}
	if len(issueAction.ExtraSigners()) != 0 {
		return errors.Errorf("expected issue action to have no extra signers, got %d", len(issueAction.ExtraSigners()))
	}
	if err := validateOutputs(issueAction.GetOutputs(), 1, 0); err != nil {
		return errors.Errorf("invalid issue outputs: %w", err)
	}
	if err := validateMetadata(metadata); err != nil {
		return errors.Errorf("invalid issue metadata: %w", err)
	}

	return nil
}

// validateTransfers validates that the actions match the transfer requests generated in env.go.
func validateTransfers(actions []any, metadata map[string][]byte) error {
	if len(actions) != 1 {
		return errors.Errorf("expected exactly 1 action for transfers, got %d", len(actions))
	}

	transferAction, ok := actions[0].(driver.TransferAction)
	if !ok {
		return errors.Errorf("action does not implement driver.TransferAction interface, got type %T", actions[0])
	}
	if transferAction.NumInputs() == 0 {
		return errors.Errorf("expected transfer action to have at least 1 input")
	}
	if transferAction.NumOutputs() == 0 {
		return errors.Errorf("expected transfer action to have at least 1 output")
	}
	if transferAction.IsGraphHiding() {
		return errors.Errorf("expected transfer action to be non-graph-hiding")
	}
	if transferAction.GetIssuer() != nil {
		return errors.Errorf("expected transfer action issuer to be nil")
	}
	for i := range transferAction.NumOutputs() {
		if transferAction.IsRedeemAt(i) {
			return errors.Errorf("transfer output %d unexpectedly marked as redeem", i)
		}
	}
	if err := validateOutputs(transferAction.GetOutputs(), transferAction.NumOutputs(), 0); err != nil {
		return errors.Errorf("invalid transfer outputs: %w", err)
	}
	if err := validateMetadata(metadata); err != nil {
		return errors.Errorf("invalid transfer metadata: %w", err)
	}

	return nil
}

// validateRedeems validates that the actions match the redeem requests generated in env.go.
func validateRedeems(actions []any, metadata map[string][]byte) error {
	if len(actions) != 1 {
		return errors.Errorf("expected exactly 1 action for redeems, got %d", len(actions))
	}

	transferAction, ok := actions[0].(driver.TransferAction)
	if !ok {
		return errors.Errorf("action does not implement driver.TransferAction interface, got type %T", actions[0])
	}
	if transferAction.NumInputs() == 0 {
		return errors.Errorf("expected redeem action to have at least 1 input")
	}
	if transferAction.NumOutputs() != 2 {
		return errors.Errorf("expected redeem action to have 2 outputs, got %d", transferAction.NumOutputs())
	}
	if transferAction.IsGraphHiding() {
		return errors.Errorf("expected redeem action to be non-graph-hiding")
	}
	if transferAction.GetIssuer() == nil {
		return errors.Errorf("expected redeem action issuer to be set")
	}

	redeemOutputs := 0
	for i := range transferAction.NumOutputs() {
		if transferAction.IsRedeemAt(i) {
			redeemOutputs++
		}
	}
	if redeemOutputs == 0 {
		return errors.Errorf("expected redeem action to have at least 1 redeem output")
	}
	if err := validateOutputs(transferAction.GetOutputs(), 2, redeemOutputs); err != nil {
		return errors.Errorf("invalid redeem outputs: %w", err)
	}
	if err := validateMetadata(metadata); err != nil {
		return errors.Errorf("invalid redeem metadata: %w", err)
	}

	return nil
}

// validateOpenPolicyRedeem validates that the actions match the open-issuer-policy
// redeem requests generated in env.go (gap 3). Unlike validateRedeems, no issuer
// identity is attached to the action: TransferSignatureValidate never requires an
// issuer signature for a redeem when PP.Issuers() is empty (open policy).
func validateOpenPolicyRedeem(actions []any, metadata map[string][]byte) error {
	if len(actions) != 1 {
		return errors.Errorf("expected exactly 1 action for open-policy redeems, got %d", len(actions))
	}

	transferAction, ok := actions[0].(driver.TransferAction)
	if !ok {
		return errors.Errorf("action does not implement driver.TransferAction interface, got type %T", actions[0])
	}
	if transferAction.NumInputs() == 0 {
		return errors.Errorf("expected open-policy redeem action to have at least 1 input")
	}
	if transferAction.NumOutputs() != 2 {
		return errors.Errorf("expected open-policy redeem action to have 2 outputs, got %d", transferAction.NumOutputs())
	}
	if transferAction.IsGraphHiding() {
		return errors.Errorf("expected open-policy redeem action to be non-graph-hiding")
	}

	redeemOutputs := 0
	for i := range transferAction.NumOutputs() {
		if transferAction.IsRedeemAt(i) {
			redeemOutputs++
		}
	}
	if redeemOutputs == 0 {
		return errors.Errorf("expected open-policy redeem action to have at least 1 redeem output")
	}
	if err := validateOutputs(transferAction.GetOutputs(), 2, redeemOutputs); err != nil {
		return errors.Errorf("invalid open-policy redeem outputs: %w", err)
	}
	if err := validateMetadata(metadata); err != nil {
		return errors.Errorf("invalid open-policy redeem metadata: %w", err)
	}

	return nil
}

// validateSwaps validates that the actions match the swap requests generated in env.go.
func validateSwaps(actions []any, metadata map[string][]byte) error {
	if len(actions) != 2 {
		return errors.Errorf("expected exactly 2 actions for swaps, got %d", len(actions))
	}

	for i, action := range actions {
		transferAction, ok := action.(driver.TransferAction)
		if !ok {
			return errors.Errorf("action %d does not implement driver.TransferAction interface, got type %T", i, action)
		}
		if transferAction.NumInputs() == 0 {
			return errors.Errorf("swap action %d has 0 inputs, expected at least 1", i)
		}
		if transferAction.NumOutputs() == 0 {
			return errors.Errorf("swap action %d has 0 outputs, expected at least 1", i)
		}
		if transferAction.IsGraphHiding() {
			return errors.Errorf("expected swap action %d to be non-graph-hiding", i)
		}
		if transferAction.GetIssuer() != nil {
			return errors.Errorf("expected swap action %d issuer to be nil", i)
		}
		for j := range transferAction.NumOutputs() {
			if transferAction.IsRedeemAt(j) {
				return errors.Errorf("swap action %d output %d unexpectedly marked as redeem", i, j)
			}
		}
		if err := validateOutputs(transferAction.GetOutputs(), transferAction.NumOutputs(), 0); err != nil {
			return errors.Errorf("invalid swap outputs for action %d: %w", i, err)
		}
	}

	if err := validateMetadata(metadata); err != nil {
		return errors.Errorf("invalid swap metadata: %w", err)
	}

	return nil
}

type fakeLedger struct{}

func (*fakeLedger) GetState(_ tk.ID) ([]byte, error) {
	panic("ciao")
}
